import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers";
import Topbar from "@/components/topbar";

const manropeSans = Manrope({
  variable: "--font-manrope-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manropeSans.variable} antialiased`}>
        <Providers>
          <Topbar />
          <main className="max-w-4xl mx-auto pt-28 px-8">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
