import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers";
import Topbar from "@/components/topbar";
import { Toaster } from "@/components/ui/sonner";

const manropeSans = Manrope({
  variable: "--font-manrope-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${manropeSans.variable} antialiased`}>
        <Providers>
          <Topbar />
          <main className="px-4 pt-28">{children}</main>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
